### ISSUE TITLE
Add Fluentd 1.14.5 to the catalog

### ISSUE THREAD

**Issue by pfmackin** [oracle-cne/catalog#13]
Add Fluentd 1.14.5 to the catalog.  This is needed by Verrazzano migration.

**Comment by pfmackin** [comment]
I installed OCNE 1.7 and see fluentd chart and app 1.6.10
fluentd-1.6.10-1            	1.6.10-1

But the image is [ghcr.io/verrazzano/fluentd-kubernetes-daemonset:v1.14.5-20230922100900-8777b84](http://ghcr.io/verrazzano/fluentd-kubernetes-daemonset:v1.14.5-20230922100900-8777b84)

Make sure the chart has the correct versions.

**Comment by mgianatagh** [comment]
After further discussion this task is not planned to happen.  The preference will be to use fluent-operator which is already in the catalog.
